### ISSUE TITLE
你好,初次运行出了问题,centos7

### ISSUE THREAD

**Issue by fy007** [pandolia/qqbot#11]
[2016-11-12 08:35:23,535] [QQBot-v1.8.2 INFO] 登录 Step8 - 获取讨论组列表
Traceback (most recent call last):
  File "/usr/bin/qqbot", line 9, in <module>
    load_entry_point('qqbot==1.8.2', 'console_scripts', 'qqbot')()
  File "/usr/lib/python2.7/site-packages/qqbot.py", line 567, in main
    bot.Login()
  File "/usr/lib/python2.7/site-packages/qqbot.py", line 71, in Login
    self.manualLogin()
  File "/usr/lib/python2.7/site-packages/qqbot.py", line 94, in manualLogin
    self.fetchDiscusses()
  File "/usr/lib/python2.7/site-packages/qqbot.py", line 298, in fetchDiscusses
    for info in result['dnamelist']:
KeyError: 'dnamelist'

**Comment by pandolia** [comment]
您好，有可能是你的qq里面没有讨论组，所以get到的result里面没有 'dnamelist' ，这种情况确实是之前没考虑到的。您试试把下面行：
    for info in result['dnamelist']:
改为：
    for info in result.get('dnamelist', []):
看看能不能运行。

**Comment by fy007** [comment]
只要第二次执行qqbot就可以了,但又出了第二个问题.
    result = json.loads(html)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[2016-11-12 09:41:45,592] [QQBot-v1.8.2 WARNING] 第1次请求“http://d1.web2.qq.com/channel/poll2”时出现“网络错误或url地址错误”，html=<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html> 



另外,我要往指定的QQ群发送消息,按教程里的方法去尝试,都发不出去,不知是怎么回事.命令如下:

-send {group} 333222 我在测试
-send group 333222 我在测试

**Comment by pandolia** [comment]
那个 WARNING 没有关系，腾讯服务器可能偶尔会返回502代码，qqbot会自动重试。

向群发消息用： -send group 577126408 你好 。注意第三个为群号，且各命令之间只有一个空格。我这边测试都是好的，你看看会不会是群号没写对。

**Comment by fy007** [comment]
[2016-11-12 14:02:08,159] [QQBot-v1.8.2 INFO] QQBot已启动，请用其他QQ号码向本QQ 飞鹰网络机器人<1296597819> 发送命令来操作QQBot。帮助命令："-help"
[2016-11-12 14:02:23,051] [QQBot-v1.8.2 INFO] 来自 buddy2454826522 的消息: "-send group 238540192 你好"
[2016-11-12 14:02:26,246] [QQBot-v1.8.2 INFO] 向 buddy2454826522 发送消息成功

在发送的QQ号上得到了这个回复.确定发送到的号码是群号
-send group 238540192 你好

接收者账号错误

**Comment by pandolia** [comment]
你运行一下 “-list group“ 命令看看那个群的群号，或者直接在 QQ 客户端里面查看群资料。"-list group" 的结果一般是： 

    203362647, 群名称, uin852340436

群号是第一个数（203362647），我感觉你这里用的可能是第三个数（uin85230436）。

**Comment by fy007** [comment]
-list group 238540192 执行后,无任何消息返回

**Comment by pandolia** [comment]
后面不要有数字

**Comment by pandolia** [comment]
-list group

**Comment by fy007** [comment]
好奇怪,list得到我群号与我在资料上看到的不相同,在群资料上看到的是这个 238540192 ,list出来的却是这个  4128540192, 贺州摩托旅游群, uin863750015,  还有,请问这个qqbot有没有群管理功能?就是审核入群的消息,并且有执行同意与否的操作.

**Comment by pandolia** [comment]
汗。。。这种情况我这边倒是没碰到过。我这边list得到的群号和群资料里面的群号都是一样的。不知道怎么回事。。。
qqbot没有群管理功能。不知道网页版qq支不支持，你试试在 "http://w.qq.com/" 网页登录qq，看看在这个网页上能不能手工操作审核入群，如果可以在网页上手工操作的话，那在qqbot上扩展实现自动操作应该也是可行的。

**Comment by fy007** [comment]
谢谢,我往 群号4128540192 发送消息成功了.

**Comment by pandolia** [comment]
不客气。
