### ISSUE TITLE
v2.1.16 ERROR

### ISSUE THREAD

**Issue by jim4node** [pandolia/qqbot#114]
[2017-04-14 09:23:38] [DEBUG] 已更新 好友 列表
[2017-04-14 09:23:53] [DEBUG] 已更新 群 列表
[2017-04-14 09:24:09] [DEBUG] 已更新 讨论组 列表
[2017-04-14 09:24:39] [DEBUG] 已更新 群“同学交流群” 的成员列表
Traceback (most recent call last):
  File "D:\Program Files\Python27\lib\logging\__init__.py", line 861, in emit
    msg = self.format(record)
  File "D:\Program Files\Python27\lib\logging\__init__.py", line 734, in format
    return fmt.format(record)
  File "D:\Program Files\Python27\lib\logging\__init__.py", line 465, in format
    record.message = record.getMessage()
  File "D:\Program Files\Python27\lib\logging\__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Logged from file qcontactdb.py, line 175

**Comment by jim4node** [comment]
qcontactdb.py, line 175 是这一句:
WARN('保存登录信息失败：%s %s', (e, picklePath))   # <-- 貌似这样的 log 写法有问题?

**Comment by jim4node** [comment]
而且, 从原有的 pickle file  自动登录失败

**Comment by pandolia** [comment]
175行那里我已经改了。
保存pickle的时候出问题，我再看一下。应该不影响使用

**Comment by jim4node** [comment]
[2017-04-14 10:05:06] [DEBUG] Exception: 'str' object is not callable
[2017-04-14 10:05:06] [WARNING] 保存登录信息失败：'str' object is not callable C:\Users\Administrato
r\.qqbot-tmp\v2.1-py2.7.13-316367718.pickle

**Comment by jim4node** [comment]
@pandolia 升级到2.1.16以后再也不能从 pickle 自动登录了, 这样调试起来很麻烦! 请尽快解决

**Comment by lixindreamer** [comment]
@pandolia 可能是Qcontact 中的 def __getattr__(self,k)  造成的这个错误

**Comment by lixindreamer** [comment]
@pandolia http://stackoverflow.com/questions/2049849/why-cant-i-pickle-this-object
你可以参考一下这个

**Comment by pandolia** [comment]
@lixindreamer 太感谢了。我按这个上面的改一下。

**Comment by pandolia** [comment]
@jim4node 已经按 @lixindreamer 等人的提供的文章修改了代码。下载最新的代码就可以使用了。主要原因是 QContact 类增加了一个 getattr 方法导致了无法 pickle 的问题。

**Comment by pandolia** [comment]
fix后的代码已上传至 pip 服务器。
