### ISSUE TITLE
运行几个小时后qq收不到bot发送的消息

### ISSUE THREAD

**Issue by ByCnck** [pandolia/qqbot#12]
日志如下，bot成功接收到了群成员消息并回复成功，但官方客户端qq群看不到该消息。
[2016-11-13 01:55:04,679] [QQBot-v1.8.2 INFO] 来自 group3417988455(buddy4254360028) 的消息: "@Asch小妹 delegate zhenxi"
['zhenxi', 53, 98.85, 10426, '12 minutes ago']
[2016-11-13 01:55:11,960] [QQBot-v1.8.2 WARNING] 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/qqbot.py", line 407, in smartRequest
    result = json.loads(html)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[2016-11-13 01:55:11,961] [QQBot-v1.8.2 WARNING] 第1次请求“http://d1.web2.qq.com/channel/send_qun_msg2”时出现“网络错误或url地址错误”，html=<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
！等待 3 秒后重新请求一次。
[2016-11-13 01:55:15,113] [QQBot-v1.8.2 INFO] 向 group3417988455 发送消息成功

^C^C^C^C[2016-11-13 01:57:32,485] [QQBot-v1.8.2 INFO] QQBot正常退出

**Comment by ByCnck** [comment]
重新用二维码扫描登陆一次就正常了

**Comment by pandolia** [comment]
您好，偶尔会有这种情况。您可以把 smartRequest 函数里面的这行：

     if retcode in (0, 1202, 100003):

改为：

     if retcode == 0:

可能会好一点。副作用是有可能一条信息会重复发送多次。

**Comment by ByCnck** [comment]
ok，多谢解答。我修改后试试
