### ISSUE TITLE
试图把自己写的东西弄到一个国外的 python 应用托管网站跑，结果出现了一个实在看不出是咋出的 403, 不知有办法没有

### ISSUE THREAD

**Issue by Yijia-Zhou** [pandolia/qqbot#143]
```
[2017-05-05 08:27:08] [INFO] 开始手动登录...
Traceback (most recent call last):
  File "/home/weizhinaihe/.virtualenvs/myvirtualenv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "/home/weizhinaihe/.virtualenvs/myvirtualenv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 810, in _prepare_proxy
    conn.connect()
  File "/home/weizhinaihe/.virtualenvs/myvirtualenv/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 294, in connect
    self._tunnel()
  File "/usr/lib/python3.5/http/client.py", line 832, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 403 Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/weizhinaihe/.virtualenvs/myvirtualenv/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/weizhinaihe/.virtualenvs/myvirtualenv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/weizhinaihe/.virtualenvs/myvirtualenv/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ui.ptlogin2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/login?daid=164&target=self&style=16&mibao_css=m_webqq&appid=501004106&enable_qlogin=0&no_verifyimg=1&s_url=http%3A%2F%2Fw.qq.com%2Fproxy.html&f_url=loginerroralert&strong_login=1&login_state=10&t=20131024001 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden',)))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "qqAI.py", line 130, in <module>
    RunBot()
  File "/home/weizhinaihe/.virtualenvs/myvirtualenv/lib/python3.5/site-packages/qqbot/qqbotcls.py", line 77, in RunBot
    runBot((botCls or QQBot), qq, user)
  File "/home/weizhinaihe/.virtualenvs/myvirtualenv/lib/python3.5/site-packages/qqbot/qqbotcls.py", line 37, in runBot
    bot.Login(qq, user)
  File "/home/weizhinaihe/.virtualenvs/myvirtualenv/lib/python3.5/site-packages/qqbot/qqbotcls.py", line 84, in Login
    session, contactdb, self.conf = QLogin(qq, user)
  File "/home/weizhinaihe/.virtualenvs/myvirtualenv/lib/python3.5/site-packages/qqbot/qsession.py", line 53, in QLogin
    session.Login(conf)
  File "/home/weizhinaihe/.virtualenvs/myvirtualenv/lib/python3.5/site-packages/qqbot/basicqsession.py", line 23, in Login
    self.prepareSession()
  File "/home/weizhinaihe/.virtualenvs/myvirtualenv/lib/python3.5/site-packages/qqbot/basicqsession.py", line 41, in prepareSession
    'https://ui.ptlogin2.qq.com/cgi-bin/login?daid=164&target=self&'
  File "/home/weizhinaihe/.virtualenvs/myvirtualenv/lib/python3.5/site-packages/qqbot/basicqsession.py", line 292, in urlGet
    return self.session.get(url, timeout=timeout)
  File "/home/weizhinaihe/.virtualenvs/myvirtualenv/lib/python3.5/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/home/weizhinaihe/.virtualenvs/myvirtualenv/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/weizhinaihe/.virtualenvs/myvirtualenv/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/weizhinaihe/.virtualenvs/myvirtualenv/lib/python3.5/site-packages/requests/adapters.py", line 485, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='ui.ptlogin2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/login?daid=164&targ
et=self&style=16&mibao_css=m_webqq&appid=501004106&enable_qlogin=0&no_verifyimg=1&s_url=http%3A%2F%2Fw.qq.com%2Fproxy.html&f_url=loginerroralert&stro
ng_login=1&login_state=10&t=20131024001 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden',)))
[2017-05-05 08:27:08] [CRITICAL] QQBOT 异常停止（code=1）
```

**Comment by pandolia** [comment]
好像是无法连接代理服务器的原因。

**Comment by pandolia** [comment]
感觉这个 403 forbidden 应该是代理服务器返回的错误。

**Comment by Yijia-Zhou** [comment]
是底层使用了代理吗？

**Comment by Yijia-Zhou** [comment]
噗……试了一下用 requests 请求别的东西，居然都是这样的错误，这网站真是有毒
