### ISSUE TITLE
Python 3.6 下使用终端命令，服务端报错

### ISSUE THREAD

**Issue by 007pig** [pandolia/qqbot#161]
QQBot 版本 2.2.16

比如我使用如下命令
`qq send buddy test hello`

服务端无法发送信息，提示：
Traceback (most recent call last):
```
  File "/Users/abc/anaconda/envs/pyshenkey/lib/python3.6/site-packages/qqbot/mainloop.py", line 21, in workAt
    func(*args, **kwargs)
  File "/Users/abc/anaconda/envs/pyshenkey/lib/python3.6/site-packages/qqbot/mysocketserver.py", line 60, in onData
    resp = self.response(data)
  File "/Users/abc/anaconda/envs/pyshenkey/lib/python3.6/site-packages/qqbot/qslots.py", line 37, in onTermCommand
    if command.startswith('GET /'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by pandolia** [comment]
感谢反馈，最新的commit 已修正此问题，尚未上传到 pip 。

**Comment by pandolia** [comment]
python2下没有这个问题。
