### ISSUE TITLE
qq群里时不时会出现消息为空的情况

### ISSUE THREAD

**Issue by pltfrplt** [pandolia/qqbot#180]
[2017-06-29 11:37:14] [INFO] 来自 群“购物街！”[成员“jj”] 的消息: ""
Traceback (most recent call last):
  File "D:\python\lib\site-packages\qqbot\mainloop.py", line 21, in workAt
    func(*args, **kwargs)
  File "D:\python\lib\site-packages\qqbot\qqbotcls.py", line 170, in onPollComplete
    self.onQQMessage(contact, member, content)
  File "D:\python\lib\site-packages\qqbot\qqbotcls.py", line 275, in <lambda>
    return lambda *a,**kw: [f(*a, **kw) for f in slots[:]]
  File "D:\python\lib\site-packages\qqbot\qqbotcls.py", line 275, in <listcomp>
    return lambda *a,**kw: [f(*a, **kw) for f in slots[:]]
  File "qrob.py", line 8, in onQQMessage
    if content[0] == '【':
IndexError: string index out of range
[2017-06-29 11:37:28] [INFO] 来自 群“购物街！”[成员“jj”] 的消息: "徒弟帮我"
[2017-06-29 11:37:38] [INFO] 来自 群“购物街！”[成员“梦幻天使”] 的消息: ""
Traceback (most recent call last):
  File "D:\python\lib\site-packages\qqbot\mainloop.py", line 21, in workAt
    func(*args, **kwargs)
  File "D:\python\lib\site-packages\qqbot\qqbotcls.py", line 170, in onPollComplete
    self.onQQMessage(contact, member, content)
  File "D:\python\lib\site-packages\qqbot\qqbotcls.py", line 275, in <lambda>
    return lambda *a,**kw: [f(*a, **kw) for f in slots[:]]
  File "D:\python\lib\site-packages\qqbot\qqbotcls.py", line 275, in <listcomp>
    return lambda *a,**kw: [f(*a, **kw) for f in slots[:]]
  File "qrob.py", line 8, in onQQMessage
    if content[0] == '【':
IndexError: string index out of range

**Comment by pandolia** [comment]
图片消息都是空消息。所以要先判断一下。
