### ISSUE TITLE
扫码后错误

### ISSUE THREAD

**Issue by chenxtdo** [pandolia/qqbot#181]
![image](https://user-images.githubusercontent.com/9393714/27772249-c631fa16-5f90-11e7-9a04-07661d5e86ed.png)

**Comment by pandolia** [comment]
这些信息还看不出来是什么错误，能否贴全一点？

**Comment by chenxtdo** [comment]
@pandolia    
Traceback (most recent call last):
  File "/usr/local/bin/qqbot", line 11, in <module>
    sys.exit(RunBot())
  File "/usr/local/lib/python2.7/site-packages/qqbot/qqbotcls.py", line 89, in RunBot
    runBot(argv)
  File "/usr/local/lib/python2.7/site-packages/qqbot/qqbotcls.py", line 44, in runBot
    bot.Login(argv)
  File "/usr/local/lib/python2.7/site-packages/qqbot/qqbotcls.py", line 104, in Login
    session, contactdb = QLogin(self.conf)
  File "/usr/local/lib/python2.7/site-packages/qqbot/qsession.py", line 50, in QLogin
    session.Login(conf)
  File "/usr/local/lib/python2.7/site-packages/qqbot/basicqsession.py", line 25, in Login
    self.getPtwebqq()
  File "/usr/local/lib/python2.7/site-packages/qqbot/basicqsession.py", line 130, in getPtwebqq
    self.urlGet(self.urlPtwebqq)
  File "/usr/local/lib/python2.7/site-packages/qqbot/basicqsession.py", line 309, in urlGet
    return self.session.get(url, timeout=timeout)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 630, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 190, in resolve_redirects
    **adapter_kwargs
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
[2017-07-03 12:29:30] [CRITICAL] QQBOT 异常停止（code=1）

**Comment by pandolia** [comment]
看上去像网络问题。系统中网页可以正常打开吗？

**Comment by chenxtdo** [comment]
@pandolia  thanks，可以了，是网络问题
