### ISSUE TITLE
无法完成登陆

### ISSUE THREAD

**Issue by redrum0003** [pandolia/qqbot#182]
今天才出现的状况，一直无法登陆上去。

[2017-07-07 11:37:01] [INFO] 开始手动登录...
[2017-07-07 11:37:01] [INFO] 已获取二维码
[2017-07-07 11:37:02] [INFO] 已将二维码发送至邮箱2681877980@qq.com
[2017-07-07 11:37:05] [INFO] 等待二维码扫描及授权...
[2017-07-07 11:37:24] [INFO] 已获授权
[2017-07-07 11:37:24] [INFO] 已获取ptwebqq
[2017-07-07 11:37:38] [ERROR] 第20次请求“http://s.web2.qq.com/api/getvfwebqq”时出现 超时, html='<html>\r\n<head><title...\r\n</body>\r\n</html>\r\n'
Traceback (most recent call last):
  File "get_qq_jdmj.py", line 180, in <module>
    RunBot()
  File "/usr/local/lib/python2.7/dist-packages/qqbot/qqbotcls.py", line 93, in RunBot
    runBot(argv)
  File "/usr/local/lib/python2.7/dist-packages/qqbot/qqbotcls.py", line 45, in runBot
    bot.Login(argv)
  File "/usr/local/lib/python2.7/dist-packages/qqbot/qqbotcls.py", line 108, in Login
    session, contactdb = QLogin(self.conf)
  File "/usr/local/lib/python2.7/dist-packages/qqbot/qsession.py", line 50, in QLogin
    session.Login(conf)
  File "/usr/local/lib/python2.7/dist-packages/qqbot/basicqsession.py", line 26, in Login
    self.getVfwebqq()
  File "/usr/local/lib/python2.7/dist-packages/qqbot/basicqsession.py", line 141, in getVfwebqq
    Origin = 'http://s.web2.qq.com'
  File "/usr/local/lib/python2.7/dist-packages/qqbot/basicqsession.py", line 404, in smartRequest
    raise RequestError
qqbot.basicqsession.RequestError
[2017-07-07 11:37:38] [CRITICAL] QQBOT 异常停止（code=1）
[2017-07-07 11:37:38] [INFO] 15秒后重新启动 QQBot （自动登陆，qq=2681877980）

**Comment by lamjack** [comment]
同个问题。

**Comment by redrum0003** [comment]
我觉得可能是QQ又搞了啥飞机

**Comment by maoyibo** [comment]
同样问题，qqbot 是从pip 安装的，版本是v2.2.18

**Comment by cjtang** [comment]
同个问题

**Comment by pandolia** [comment]
今天webqq的服务器挂了。

**Comment by pandolia** [comment]
现在应该恢复正常了。

**Comment by Easenguard** [comment]
同问题，时好时坏
