### ISSUE TITLE
安装了qqbot但是没有这个指令？

### ISSUE THREAD

**Issue by Ninzero** [pandolia/qqbot#212]
`bash: qqbot: command not found`

**Comment by Ninzero** [comment]
`pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
APScheduler (3.3.1)
certifi (2017.7.27.1)
chardet (3.0.4)
idna (2.6)
pip (9.0.1)
pytz (2017.2)
qqbot (2.3.5)
requests (2.18.4)
setuptools (28.8.0)
six (1.11.0)
tzlocal (1.4)
urllib3 (1.22)`

**Comment by pandolia** [comment]
用 python -m qqbot 命令

**Comment by Ninzero** [comment]
emmmmm但是……
`Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/python3/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/python3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/python3/lib/python3.6/site-packages/qqbot/__init__.py", line 3, in <module>
    from .qqbotcls import QQBot, QQBotSlot, QQBotSched, RunBot, _bot
  File "/usr/local/python3/lib/python3.6/site-packages/qqbot/qqbotcls.py", line 22, in <module>
    from qqbot.qsession import QLogin, RequestError
  File "/usr/local/python3/lib/python3.6/site-packages/qqbot/qsession.py", line 10, in <module>
    from qqbot.qcontactdb import QContactDB
  File "/usr/local/python3/lib/python3.6/site-packages/qqbot/qcontactdb/__init__.py", line 1, in <module>
    from .qcontactdb import QContactDB
  File "/usr/local/python3/lib/python3.6/site-packages/qqbot/qcontactdb/qcontactdb.py", line 8, in <module>
    from qqbot.qcontactdb.contactdb import ContactDB
  File "/usr/local/python3/lib/python3.6/site-packages/qqbot/qcontactdb/contactdb.py", line 3, in <module>
    import sqlite3, traceback
  File "/usr/local/python3/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/python3/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'`

**Comment by pandolia** [comment]
你的系统里面的 sqlite3 没装好。试一下： sudo apt-get install sqlite3

**Comment by Ninzero** [comment]
已解决，多谢了
