### ISSUE TITLE
插件放在工作目录 ~/.qqbot-tmp/plugins/下面无法加载呢

### ISSUE THREAD

**Issue by 33201** [pandolia/qqbot#214]
说找不到插件，非放置在程序的plugins/目录下才可以找的到。
还有一个问题就是讨论组的@ME不支持呢

**Comment by pandolia** [comment]
发一下你启动时控制台打印的log。

**Comment by pandolia** [comment]
讨论组 @ 功能见： https://github.com/pandolia/qqbot/issues/191

**Comment by 33201** [comment]
谢谢回复。
[2017-09-26 11:01:03] [ERROR] 
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/qqbot/qqbotcls.py", line 278, in Plug
    module = Import(moduleName)
  File "/srv/homeassistant/lib/python3.6/site-packages/qqbot/common.py", line 201, in Import
    __import__(moduleName)
ModuleNotFoundError: No module named 'qqbot.plugins.xiaoi'
[2017-09-26 11:01:03] [ERROR] 错误：无法加载插件 qqbot.plugins.xiaoi ，<class 'ModuleNotFoundError'>: No module named 'qqbot.plugins.xiaoi'
[2017-09-26 11:01:03] [INFO] 开始自动登录...
这是启动日志

**Comment by pandolia** [comment]
qqbot.plugins.xiaoi 改成 xiaoi 。

**Comment by 33201** [comment]
可以了，谢谢
