### ISSUE TITLE
获取群列表时出错

### ISSUE THREAD

**Issue by GeiliCode** [pandolia/qqbot#22]
```
[2016-12-22 11:21:16] [INFO] 获取朋友列表成功，共 399 个朋友
[2016-12-22 11:21:16] [INFO] 登录 Step7 - 获取群列表
[2016-12-22 11:21:16] [INFO] ============================================================
Traceback (most recent call last):
  File "/Users/xyz/.anaconda2/bin/qqbot", line 11, in <module>
    sys.exit(main())
  File "/Users/xyz/.anaconda2/lib/python2.7/site-packages/qqbot/qqbot.py", line 24, in main
    bot.Login()
  File "/Users/xyz/.anaconda2/lib/python2.7/site-packages/qqbot/qqbot.py", line 50, in Login
    self.manualLogin()
  File "/Users/xyz/.anaconda2/lib/python2.7/site-packages/qqbot/qqbot.py", line 62, in manualLogin
    self.fetchGroups()
  File "/Users/xyz/.anaconda2/lib/python2.7/site-packages/qqbot/qqbot.py", line 312, in fetchGroups
    member = self.fetchGroupMember(info['code'])
  File "/Users/xyz/.anaconda2/lib/python2.7/site-packages/qqbot/qqbot.py", line 351, in fetchGroupMember
    minfos = ret['minfo']
KeyError: 'minfo'
```

**Comment by pandolia** [comment]
有时候是这样的，再运行一次就可以了。

**Comment by GeiliCode** [comment]
非常感谢, 可以正常运行了.
