### ISSUE TITLE
提一个 bug ，irc 插件，如果获得好友恢复会有命令行的提示错误

### ISSUE THREAD

**Issue by ferocknew** [pandolia/qqbot#232]
提示如下：

```
[2017-11-01 13:40:11] [INFO] 来自 好友“uin45503824” 的消息: " ok？"
[2017-11-01 13:40:11] [ERROR] 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/qqbot/qqbotcls.py", line 99, in _call
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/qqbot/plugins/miniirc.py", line 244, in onQQMessage
    self.buddies.add(buddy)
  File "/usr/local/lib/python2.7/site-packages/qqbot/plugins/miniirc.py", line 306, in add
    if contact.uin in self.uins:
AttributeError: 'NoneType' object has no attribute 'uin'
[2017-11-01 13:40:11] [ERROR] 执行 qqbot.plugins.miniirc.onQQMessage 时出错，'NoneType' object has no attribute 'uin'
[2017-11-01 13:40:11] [ERROR] 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/qqbot/qqbotcls.py", line 99, in _call
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/qqbot/plugins/miniirc.py", line 244, in onQQMessage
    self.buddies.add(buddy)
  File "/usr/local/lib/python2.7/site-packages/qqbot/plugins/miniirc.py", line 306, in add
    if contact.uin in self.uins:
AttributeError: 'NoneType' object has no attribute 'uin'
[2017-11-01 13:40:11] [ERROR] 执行 qqbot.plugins.miniirc.onQQMessage 时出错，'NoneType' object has no attribute 'uin'

```

**Comment by ferocknew** [comment]
如果修复了告知一下，我更新一下，日志信息
```
[2017-11-01 13:27:01] [INFO] QQBot-v2.3.6
[2017-11-01 13:27:01] [INFO] Python 2.7.13
```

**Comment by pandolia** [comment]
好的。感谢提醒！

**Comment by pandolia** [comment]
这个是自己发消息引起的吗？

**Comment by ferocknew** [comment]
提供所有错误的日志
```
2017-11-01 13:29:08] [INFO] 已获取并更新 好友列表
[2017-11-01 13:29:08] [INFO] 来自 好友“uin45503824” 的消息: "1111"
[2017-11-01 13:29:08] [ERROR] 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/qqbot/qqbotcls.py", line 99, in _call
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/qqbot/plugins/miniirc.py", line 244, in onQQMessage
    self.buddies.add(buddy)
  File "/usr/local/lib/python2.7/site-packages/qqbot/plugins/miniirc.py", line 306, in add
    if contact.uin in self.uins:
AttributeError: 'NoneType' object has no attribute 'uin'
[2017-11-01 13:29:08] [ERROR] 执行 qqbot.plugins.miniirc.onQQMessage 时出错，'NoneType' object has no attribute 'uin'
[2017-11-01 13:29:11] [INFO] 向 好友“兼哲” 发消息成功：哈
[2017-11-01 13:29:11] [INFO] 正在获取 好友列表 ...
[2017-11-01 13:29:11] [INFO] 已获取并更新 好友列表
[2017-11-01 13:29:11] [INFO] 来自 好友“uin45503824” 的消息: "哈"
[2017-11-01 13:29:11] [ERROR] 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/qqbot/qqbotcls.py", line 99, in _call
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/qqbot/plugins/miniirc.py", line 244, in onQQMessage
    self.buddies.add(buddy)
  File "/usr/local/lib/python2.7/site-packages/qqbot/plugins/miniirc.py", line 306, in add
    if contact.uin in self.uins:
AttributeError: 'NoneType' object has no attribute 'uin'
[2017-11-01 13:29:11] [ERROR] 执行 qqbot.plugins.miniirc.onQQMessage 时出错，'NoneType' object has no attribute 'uin'
[2017-11-01 13:29:32] [INFO] 来自 好友“兼哲” 的消息: "右边"
[2017-11-01 13:29:34] [INFO] 来自 好友“兼哲” 的消息: "有病"
[2017-11-01 13:39:51] [INFO] 向 好友“兼哲” 发消息成功：1
[2017-11-01 13:39:51] [INFO] 正在获取 好友列表 ...
[2017-11-01 13:39:52] [INFO] 已获取并更新 好友列表
[2017-11-01 13:39:52] [INFO] 来自 好友“uin45503824” 的消息: "1"
[2017-11-01 13:39:52] [ERROR] 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/qqbot/qqbotcls.py", line 99, in _call
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/qqbot/plugins/miniirc.py", line 244, in onQQMessage
    self.buddies.add(buddy)
  File "/usr/local/lib/python2.7/site-packages/qqbot/plugins/miniirc.py", line 306, in add
    if contact.uin in self.uins:
AttributeError: 'NoneType' object has no attribute 'uin'
[2017-11-01 13:39:52] [ERROR] 执行 qqbot.plugins.miniirc.onQQMessage 时出错，'NoneType' object has no attribute 'uin'
[2017-11-01 13:39:52] [ERROR] 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/qqbot/qqbotcls.py", line 99, in _call
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/qqbot/plugins/miniirc.py", line 244, in onQQMessage
    self.buddies.add(buddy)
  File "/usr/local/lib/python2.7/site-packages/qqbot/plugins/miniirc.py", line 306, in add
    if contact.uin in self.uins:
AttributeError: 'NoneType' object has no attribute 'uin'
[2017-11-01 13:39:52] [ERROR] 执行 qqbot.plugins.miniirc.onQQMessage 时出错，'NoneType' object has no attribute 'uin'
[2017-11-01 13:39:58] [INFO] 来自 好友“兼哲” 的消息: " /表情 "
[2017-11-01 13:40:08] [INFO] 向 好友“兼哲” 发消息成功：不要发表情
[2017-11-01 13:40:08] [INFO] 正在获取 好友列表 ...
[2017-11-01 13:40:09] [INFO] 已获取并更新 好友列表
[2017-11-01 13:40:09] [INFO] 来自 好友“uin45503824” 的消息: "不要发表情"
[2017-11-01 13:40:09] [ERROR] 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/qqbot/qqbotcls.py", line 99, in _call
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/qqbot/plugins/miniirc.py", line 244, in onQQMessage
    self.buddies.add(buddy)
  File "/usr/local/lib/python2.7/site-packages/qqbot/plugins/miniirc.py", line 306, in add
    if contact.uin in self.uins:
AttributeError: 'NoneType' object has no attribute 'uin'
[2017-11-01 13:40:09] [ERROR] 执行 qqbot.plugins.miniirc.onQQMessage 时出错，'NoneType' object has no attribute 'uin'
[2017-11-01 13:40:09] [ERROR] 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/qqbot/qqbotcls.py", line 99, in _call
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/qqbot/plugins/miniirc.py", line 244, in onQQMessage
    self.buddies.add(buddy)
  File "/usr/local/lib/python2.7/site-packages/qqbot/plugins/miniirc.py", line 306, in add
    if contact.uin in self.uins:
AttributeError: 'NoneType' object has no attribute 'uin'
[2017-11-01 13:40:09] [ERROR] 执行 qqbot.plugins.miniirc.onQQMessage 时出错，'NoneType' object has no attribute 'uin'
[2017-11-01 13:40:10] [INFO] 向 好友“兼哲” 发消息成功： ok？
[2017-11-01 13:40:10] [INFO] 正在获取 好友列表 ...
[2017-11-01 13:40:11] [INFO] 已获取并更新 好友列表
[2017-11-01 13:40:11] [INFO] 来自 好友“uin45503824” 的消息: " ok？"
[2017-11-01 13:40:11] [ERROR] 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/qqbot/qqbotcls.py", line 99, in _call
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/qqbot/plugins/miniirc.py", line 244, in onQQMessage
    self.buddies.add(buddy)
  File "/usr/local/lib/python2.7/site-packages/qqbot/plugins/miniirc.py", line 306, in add
    if contact.uin in self.uins:
AttributeError: 'NoneType' object has no attribute 'uin'
[2017-11-01 13:40:11] [ERROR] 执行 qqbot.plugins.miniirc.onQQMessage 时出错，'NoneType' object has no attribute 'uin'
[2017-11-01 13:40:11] [ERROR] 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/qqbot/qqbotcls.py", line 99, in _call
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/qqbot/plugins/miniirc.py", line 244, in onQQMessage
    self.buddies.add(buddy)
  File "/usr/local/lib/python2.7/site-packages/qqbot/plugins/miniirc.py", line 306, in add
    if contact.uin in self.uins:
AttributeError: 'NoneType' object has no attribute 'uin'
[2017-11-01 13:40:11] [ERROR] 执行 qqbot.plugins.miniirc.onQQMessage 时出错，'NoneType' object has no attribute 'uin'
[2017-11-01 13:
```

**Comment by ferocknew** [comment]
过程就是，A qq 通过 bot 登录，B QQ 从软件上给 A QQ 发送消息。
此时，weechat 客户端已链接 qqbot irc 服务器。
weechat 出现对话框，然后，在对话框内回复 B，B QQ 再从软件上回复 A ，此时出现这个报错。

**Comment by ferocknew** [comment]
从日志上看，的确像 发送了 消息以后，又给自己发了一条。。。。

**Comment by ferocknew** [comment]
```
2017-11-01 18:47:14] [INFO] 来自 好友“uin3012024713” 的消息: "！"
[2017-11-01 18:47:14] [INFO] 向 好友“uin3012024713” 发消息成功：感叹啊！
[2017-11-01 18:47:18] [INFO] 来自 好友“兼哲” 的消息: "哈哈哈哈"
[2017-11-01 18:47:18] [INFO] 向 好友“兼哲” 发消息成功：小主人这么开心呀。看到小主人开心我也好开心呢。
[2017-11-01 18:47:18] [INFO] 正在获取 好友列表 ...
[2017-11-01 18:47:18] [WARNING] 因存在重名或名称中含特殊字符，无法绑定以下好友的真实QQ号，请修改其备注名，保证备注名的唯一性且不带特殊字符：
	好友“兼哲”(uin=3396032217)
	好友“兼哲”(uin=460803469)
[2017-11-01 18:47:18] [INFO] 已获取并更新 好友列表
[2017-11-01 18:47:18] [INFO] 来自 好友“uin3012024713” 的消息: "小主人这么开心呀。看到小主人开心我也好开心呢。"
[2017-11-01 18:47:19] [INFO] 向 好友“uin3012024713” 发消息成功：给你点个赞。
[2017-11-01 18:47:21] [INFO] 来自 好友“兼哲” 的消息: "今天天气如何"
[2017-11-01 18:47:21] [INFO] 向 好友“兼哲” 发消息成功：山东济南:11月1号 周三,12-24° 19° 晴转多云 南风微风;11月2号 周四,12-23° 多云 南风微风;11月3号 周五,11-15° 多云 北风4-5级;11月4号 周六,10-17° 多云 东北风3-4级;
[2017-11-01 18:47:22] [INFO] 正在获取 好友列表 ...
[2017-11-01 18:47:22] [WARNING] 因存在重名或名称中含特殊字符，无法绑定以下好友的真实QQ号，请修改其备注名，保证备注名的唯一性且不带特殊字符：
	好友“兼哲”(uin=3396032217)
	好友“兼哲”(uin=460803469)
[2017-11-01 18:47:22] [INFO] 已获取并更新 好友列表
[2017-11-01 18:47:22] [INFO] 来自 好友“uin3012024713” 的消息: "山东济南:11月1号 周三,12-24° 19° 晴转多云 南风微风;11月2号 周四,12-23° 多云 南风微风;11月3号 周五,11-15° 多云 北风4-5级;11月4号 周六,10-17° 多云 东北风3-4级;"
[2017-11-01 18:47:22] [INFO] 向 好友“uin3012024713” 发消息成功：再说点别的吧。
[2017-11-01 18:48:58] [INFO] 正在获取 好友列表 ...
[2017-11-01 18:48:59] [WARNING] 因存在重名或名称中含特殊字符，无法绑定以下好友的真实QQ号，请修改其备注名，保证备注名的唯一性且不带特殊字符：
	好友“兼哲”(uin=3396032217)
	好友“兼哲”(uin=460803469)
[2017-11-01 18:48:59] [INFO] 已获取并更新 好友列表
[2017-11-01 18:48:59] [INFO] 来自 好友“uin3012024713” 的消息: "你可以测试了"
[2017-11-01 18:48:59] [INFO] 向 好友“uin3012024713” 发消息成功：测试完成之后就可以了
[2017-11-01 18:49:29] [INFO] 来自 好友“兼哲” 的消息: "你麻痹"
[2017-11-01 18:49:29] [INFO] 向 好友“兼哲” 发消息成功：你这样说话我很不喜欢。
[2017-11-01 18:49:29] [INFO] 正在获取 好友列表 ...
[2017-11-01 18:49:29] [WARNING] 因存在重名或名称中含特殊字符，无法绑定以下好友的真实QQ号，请修改其备注名，保证备注名的唯一性且不带特殊字符：
	好友“兼哲”(uin=3396032217)
	好友“兼哲”(uin=460803469)
[2017-11-01 18:49:29] [INFO] 已获取并更新 好友列表
[2017-11-01 18:49:29] [INFO] 来自 好友“uin3012024713” 的消息: "你这样说话我很不喜欢。"
[2017-11-01 18:49:30] [INFO] 向 好友“uin3012024713” 发消息成功：好吧，我道歉啦，不过小主人要告诉我应该怎么样哦。
```

发现一个现象，如果手机 QQ 也登录，qqbot 也开着，会自己和自己说话。。。

**Comment by pandolia** [comment]
@ferocknew 最新的commit应该已经修正了这个问题，麻烦帮忙测试一下： https://github.com/pandolia/qqbot/archive/master.zip

**Comment by pandolia** [comment]
下载源码后，cd到该目录并运行”pip install ."
