### ISSUE TITLE
启动时时报sslerror(certificateerror(

### ISSUE THREAD

**Issue by andares** [pandolia/qqbot#234]
完整信息如下：

```
[2017-11-08 13:44:44] [INFO] QQBot-v2.3.7
[2017-11-08 13:44:44] [INFO] Python 2.7.6
[2017-11-08 13:44:44] [INFO] 工作目录：/root/.qqbot-tmp
[2017-11-08 13:44:44] [INFO] 配置文件：/root/.qqbot-tmp/v2.3.conf
[2017-11-08 13:44:44] [INFO] 用户名：无
[2017-11-08 13:44:44] [INFO] 登录方式：手动
[2017-11-08 13:44:44] [INFO] 命令行服务器端口号：8188
[2017-11-08 13:44:44] [INFO] 二维码服务器 ip ：无
[2017-11-08 13:44:44] [INFO] 二维码服务器端口号：无
[2017-11-08 13:44:44] [INFO] 用于接收二维码的邮箱账号：无
[2017-11-08 13:44:44] [INFO] 邮箱服务授权码：无
[2017-11-08 13:44:44] [INFO] 以文本模式显示二维码：否
[2017-11-08 13:44:44] [INFO] 调试模式：关闭
[2017-11-08 13:44:44] [INFO] 掉线后自动重启：否
[2017-11-08 13:44:44] [INFO] 后台模式（daemon 模式）：否
[2017-11-08 13:44:44] [INFO] 启动方式：快速启动（登录成功后立即启动）
[2017-11-08 13:44:44] [INFO] 插件目录1：/root/.qqbot-tmp/plugins
[2017-11-08 13:44:44] [INFO] 启动时需要加载的插件：['qqbot.plugins.sampleslots', 'qqbot.plugins.sch
edrestart']
[2017-11-08 13:44:44] [INFO] 成功：加载插件 qqbot.plugins.sampleslots（回调函数['onUpdate', 'onPlug
', 'onInterval', 'onStartupComplete', 'onQrcode', 'onUnplug', 'onInit', 'onQQMessage', 'onExit']、
定时任务[]）
[2017-11-08 13:44:44] [INFO] 成功：加载插件 qqbot.plugins.schedrestart（回调函数['onPlug', 'onUnplu
g']、定时任务[]）
[2017-11-08 13:44:44] [INFO] 开始手动登录...
/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/bin/qqbot", line 9, in <module>
    load_entry_point('qqbot==v2.3.7', 'console_scripts', 'qqbot')()
  File "/usr/local/lib/python2.7/dist-packages/qqbot/qqbotcls.py", line 93, in RunBot
    runBot(argv)
  File "/usr/local/lib/python2.7/dist-packages/qqbot/qqbotcls.py", line 45, in runBot
    bot.Login(argv)
  File "/usr/local/lib/python2.7/dist-packages/qqbot/qqbotcls.py", line 108, in Login
    session, contactdb = QLogin(self.conf)
  File "/usr/local/lib/python2.7/dist-packages/qqbot/qsession.py", line 50, in QLogin
    session.Login(conf)
  File "/usr/local/lib/python2.7/dist-packages/qqbot/basicqsession.py", line 33, in Login
    self.prepareSession()
  File "/usr/local/lib/python2.7/dist-packages/qqbot/basicqsession.py", line 51, in prepareSession
    'https://ui.ptlogin2.qq.com/cgi-bin/login?daid=164&target=self&'
  File "/usr/local/lib/python2.7/dist-packages/qqbot/basicqsession.py", line 317, in urlGet
    return self.session.get(url, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ui.ptlogin2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/login?daid=164&target=self&style=16&mibao_css=m_webqq&appid=501004106&enable_qlogin=0&no_verifyimg=1&s_url=http%3A%2F%2Fw.qq.com%2Fproxy.html&f_url=loginerroralert&strong_login=1&login_state=10&t=20131024001 (Caused by SSLError(CertificateError("hostname 'ui.ptlogin2.qq.com' doesn't match either of '*.mvs.qq.com', 'mvs.qq.com'",),))
[2017-11-08 13:44:44] [CRITICAL] QQBOT 异常停止（code=1）
```

早上还好好的，突然就这样了。删除tmp目录没用，我卸载了重新安装也一样。但是最后报的hostname匹配不对的域名在变。之前是

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ssl.ptlogin2.qq.com', port=443): Max retries exceeded with url: /ptqrlogin?ptqrtoken=1178303247&webqq_type=10&remember_uin=1&login2qq=1&aid=501004106&u1=http%3A%2F%2Fw.qq.com%2Fproxy.html%3Flogin2qq%3D1%26webqq_type%3D10&ptredirect=0&ptlang=2052&daid=164&from_ui=1&pttype=1&dumy=&fp=loginerroralert&action=0-0-1348102.8297369776&mibao_css=m_webqq&t=undefined&g=1&js_type=0&js_ver=10141&login_sig=&pt_randsalt=0 (Caused by SSLError(CertificateError("hostname 'ssl.ptlogin2.qq.com' doesn't match either of '*.panda.qq.com', 'panda.qq.com'",),))
```

**Comment by andares** [comment]
重装加删目录好了。。

**Comment by pandolia** [comment]
可能是网络问题。
