### ISSUE TITLE
安装问题求助

### ISSUE THREAD

**Issue by andares** [pandolia/qqbot#236]
最近在公司服务器使用pip安装一直报错，我已经尝试了下载master打包的zip文件解压后运行了，还是报这个错误。

日志也看了，是不是某个模块的下载地址被墙？

```
# pip install .
Unpacking /root/qqbot-master
  Running setup.py (path:/tmp/pip-m3CkAp-build/setup.py) egg_info for package from file:///root/qqbot-master

Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages (from qqbot==v2.3.7)
Downloading/unpacking certifi (from qqbot==v2.3.7)
  Downloading certifi-2017.11.5-py2.py3-none-any.whl (330kB): 86kB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 572, in unpack_http_url
    download_hash = _download_url(resp, link, temp_location)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 433, in _download_url
    for chunk in resp_read(4096):
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 421, in resp_read
    chunk_size, decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/response.py", line 225, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/response.py", line 174, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 602, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
SSLError: The read operation timed out
```

**Comment by pandolia** [comment]
这个是网络问题吧。

**Comment by pandolia** [comment]
下载不了 certifi-2017.11.5-py2.py3-none-any.whl 这个文件。

**Comment by andares** [comment]
好像是访问不到 https://pypi.python.org/packages/29/9b/25ef61e948321296f029f53c9f67cc2b54e224db509eb67ce17e0df6044a/certifi-2017.11.5-py2.py3-none-any.whl#md5=429fdf238d878f8090a80ccc3488049b 哎这叫什么事儿啊
