### ISSUE TITLE
新增加了一个 passwordlogin 插件，免去人工扫码的烦恼

### ISSUE THREAD

**Issue by pandolia** [pandolia/qqbot#240]
详见：[passwordlogin](https://github.com/pandolia/qqbot/blob/master/qqbot/plugins/passwordlogin.py)

**Comment by kawhiLin** [comment]
请问我装了selenium模块后，加载插件的时候报错ImportError: No module named selenium，
为什么只有在qqbot里面才会找不到这个模块，别的项目import selenium都没问题？

**Comment by XianwuLin** [comment]
我看了下 插件，为啥里面一堆的time.sleep呀？然后我试了一下，果然没登录成功……

**Comment by pandolia** [comment]
可能你把 selenium 安装到 python3 的库里面去了，而 qqbot 是用 python2 启动的。

**Comment by kawhiLin** [comment]
是装在python2的库里的，重启了也没用。

**Comment by pandolia** [comment]
你看下启动 qqbot 是用的 python2 还是 python3 ？

**Comment by pandolia** [comment]
看启动 qqbot 时控制台的第二条 log 。

**Comment by kawhiLin** [comment]
是python2，很奇怪。

**Comment by kawhiLin** [comment]
Python 2.7.14。没问题诶

**Comment by babyfiv5** [comment]
请问有没有必要加入一下滑块验证的代码，我测试了这个模块，有时能登录成功有时失败，看了一下好像是有时需要滑块验证

**Comment by pandolia** [comment]
我倒是还没碰到滑块验证的情况。

**Comment by babyfiv5** [comment]
确实会出现滑块验证，不是偶然现象，今天早晨自动登录的时候又出现了，而且这次我关掉qqbot重新启动依然出现滑块验证，在登录qq空间的时候。

**Comment by 276562578** [comment]
报错
https://i.imgur.com/C2iK8fl.png

**Comment by 276562578** [comment]
注册了个新号
https://i.imgur.com/g7AF29j.png

**Comment by pandolia** [comment]
@276562578 应该是出滑块验证了，你可以先尝试手工打开浏览器登录 m.qzone.com 。登录成功后应该是一段时间内都不会出滑块验证了。

**Comment by 276562578** [comment]
刚尝试了一下，还是提示第二个图
手机浏览器登陆没有出现验证码或滑块
登陆后依旧不行

**Comment by 276562578** [comment]
我们不可以直接使用从浏览器中提取出的cookie作为身份认证吗？

**Comment by pandolia** [comment]
除了cookie，还需要另外一些数据，才能通过身份验证。具体你看下插件的代码吧。

**Comment by 276562578** [comment]
输入账号的前面应该加一句clear()清空qq号输入部分，确保不会被账号记忆功能干扰，我昨天手动试的时候出现了这个问题。
后来试来试去就出滑块悲剧了。。另外我找到了个不错的解决滑块问题的文章，http://www.360doc.cn/article/5315_665775043.html

希望可以帮到你

**Comment by pandolia** [comment]
@276562578 感谢帮忙，我研究一下。

**Comment by defsky** [comment]
@276562578 我也是这个错误

**Comment by 276562578** [comment]
@defsky 你试试添加截图代码，然后看下截图，是什么问题

**Comment by defsky** [comment]
@276562578 代码是啥？在哪里添加呢？

**Comment by 276562578** [comment]
@defsky 你可以查看下代码，很简单，截图代码可以搜索引擎

**Comment by defsky** [comment]
@276562578 用这句driver.save_screenshot('exception.png') 在异常触发之后截图发现是个滑块验证

**Comment by coolwind8214** [comment]
![image](https://user-images.githubusercontent.com/32867316/34033980-85015092-e1b7-11e7-81ef-81a774952618.png)

**Comment by coolwind8214** [comment]
这个是啥问题？

**Comment by coolwind8214** [comment]
用的是PhantomJS

**Comment by 276562578** [comment]
@coolwind8214 参考上述

**Comment by BlueCat0** [comment]
`````
[2017-12-16 16:52:15] [ERROR] 用户名-密码登录失败，原因：Message: Service phanto                                                                                                                                   mjs unexpectedly exited. Status code was: -6
Traceback (most recent call last):
  File "/root/.qqbot-tmp/plugins/passwordlogin.py", line 56, in Login
    self.newLogin(conf)
  File "/root/.qqbot-tmp/plugins/passwordlogin.py", line 65, in newLogin
    driver = getattr(webdriver, driverType)()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/phantomjs/webd                                                                                                                                   river.py", line 52, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service                                                                                                                                   .py", line 96, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service                                                                                                                                   .py", line 109, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service phantomjs unexpe                                                                                                                                   ctedly exited. Status code was: -6


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.qqbot-tmp/plugins/passwordlogin.py", line 58, in Login
    self.newLogin(conf)
  File "/root/.qqbot-tmp/plugins/passwordlogin.py", line 65, in newLogin
    driver = getattr(webdriver, driverType)()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/phantomjs/webd                                                                                                                                   river.py", line 52, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service                                                                                                                                   .py", line 96, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service                                                                                                                                   .py", line 109, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service phantomjs unexpe                                                                                                                                   ctedly exited. Status code was: -6
````
PhantomJS Ubuntu16 64 Python3
请问这是什么问题……

**Comment by 276562578** [comment]
@BlueCat0 你的phantomjs安装有问题，请看注释部分，先确认phantomjs能用

**Comment by BlueCat0** [comment]
@276562578 感谢，是我疏忽了，是phantomjs的安装问题
Ubuntu16的apt-get方式安装的phantomjs是有问题的==
从官网下载手动安装就没有问题
（具体安装方法http://www.cnblogs.com/web424/p/6755851.html


然鹅
出了滑块验证
我还是乖乖扫码吧==

**Comment by coolwind8214** [comment]
@276562578 我的那个问题参考上面的都处理过了，还是不行。。，这个是滑块问题？还是cookie问题？

**Comment by LakorTi** [comment]
@pandolia 使用phantomjs登录后，不管是否登录成功（未登录成功即扫码登录），后台都会一直挂着两个任务，这是什么问题呢？
pi       15046 15042  0 Dec18 ?        00:00:27 phantomjs --cookies-file=/tmp/tmplnxx0om2 --webdriver=35665
pi       15067 15042  0 Dec18 ?        00:00:27 phantomjs --cookies-file=/tmp/tmpmv5ooteu --webdriver=37413

**Comment by lvusyy** [comment]
折腾好久.使用各种办法.最终也没弄搞定!
win下面  phantomjs 测试都OK 放到服务器就不行. 开始有时候可以后来直接不行了...
感觉phantomjs被识别出来了. 已经加了heads 伪装了.
服务器上没装桌面不然直接 chrome或Firefox 一定没问题的...

**Comment by lvusyy** [comment]
@LakorTi  phantomjs 残留进程. 因为异常之后没有关闭所以一直残留系统中的. 完全可以关闭.
以为你下次调用会自动生成新的pantomjs的进程.

**Comment by lvusyy** [comment]
自己改代码测试了.暂时登录没有问题了.

我使用 chrome 方式. phantomjs,总是遇到各种问题. 我太菜了,没办法.只能chrome了.
1.安装chrome.
2.下载匹配的chromedrive
chromedriver下载地址,
http://npm.taobao.org/mirrors/chromedriver/
3.关于服务器没有桌面的
` #安装Xvfb和pyvirtualdisplay

yum install xorg-x11-server-Xvfb

pip install pyvirtualdisplay
`
在chrome被初始化前运行
`from pyvirtualdisplay import Display

from selenium import webdriver

display = Display(visible=0, size=(900, 800))

display.start()
`
4.关于root权限运行 chrome会提示权限问题.可以临时用别的用户运行
` 新建一个用户
然后使用命令切换过去.如
`runuser -l username -c 'python3 qqbot.py'`

暂时没问题... 
关于滑块条问题.我自己测试了下. 直接一次性输入登录用户名密码,会被识别.
我自己加了延时,和拆分了字符串,一次一个字符输入.中间加了 随机50-600 毫秒的延时.目前没有发现什么问题.

**Comment by YBA0312** [comment]
小白不懂，这是什么情况？？？
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/qqbot-2.3.7-py3.5.egg/qqbot/qqbotcls.py", line 282, in Plug
    module = Import(moduleName)
  File "/usr/local/lib/python3.5/dist-packages/qqbot-2.3.7-py3.5.egg/qqbot/common.py", line 201, in Import
    __import__(moduleName)
ImportError: No module named 'passwordlogin'

**Comment by yuansuye** [comment]
@YBA0312 你没有passwordlogin插件，要自己下一个

**Comment by yuansuye** [comment]
windows server 2008 r2. 无法实现密码登录。一直提示密码错误。。换了两三个号都不行。手动输入也一样。chrome和firefox都试了，一样的密码错误。求救。。
[https://wx1.sinaimg.cn/mw690/d7030a5cgy1fmzyhz7uhij216d0rgq3b.jpg](url)
[https://wx1.sinaimg.cn/mw690/d7030a5cgy1fmzyi0hui3j20l80dvaa1.jpg](url)

**Comment by yuansuye** [comment]
用了passwordlogin插件后, 设置daemon为后台模式失败.

**Comment by pandolia** [comment]
出滑块验证码的问题，建议先手工打开浏览器用密码登录几次，之后基本上就不会出滑块验证码了。如果是服务器，建议先在服务器上开一个代理，再在本地电脑上用浏览器连接这个代理登录几次。
