### ISSUE TITLE
接收消息出错，一直收不到消息，手动重启后又可以收到消息了，也不报这个错误

### ISSUE THREAD

**Issue by 1098880928aa** [pandolia/qqbot#268]
[2018-01-12 14:21:40] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"errmsg":"error","retcode":103}'
[2018-01-12 14:21:40] [ERROR] 接收消息出错，开始测试登录 cookie 是否过期...
[2018-01-12 14:21:40] [INFO] 登录成功。登录账号：淡定(1098880928)
[2018-01-12 14:21:40] [INFO] 登录 cookie 尚未过期
[2018-01-12 16:32:07] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"errmsg":"error","retcode":103}'
[2018-01-12 16:32:07] [ERROR] 接收消息出错，开始测试登录 cookie 是否过期...
[2018-01-12 16:32:07] [INFO] 登录成功。登录账号：淡定(1098880928)
[2018-01-12 16:32:07] [INFO] 登录 cookie 尚未过期
[2018-01-12 19:01:57] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"errmsg":"error","r...st[59.983457313s]"}\n'
[2018-01-12 19:01:57] [ERROR] 接收消息出错，开始测试登录 cookie 是否过期...
[2018-01-12 19:01:57] [INFO] 登录成功。登录账号：淡定(1098880928)
[2018-01-12 19:01:57] [INFO] 登录 cookie 尚未过期
[2018-01-12 19:05:59] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"errmsg":"error","r...st[59.957160397s]"}\n'
[2018-01-12 19:05:59] [ERROR] 接收消息出错，开始测试登录 cookie 是否过期...
[2018-01-12 19:05:59] [INFO] 登录成功。登录账号：淡定(1098880928)
[2018-01-12 19:05:59] [INFO] 登录 cookie 尚未过期
[2018-01-12 19:06:00] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"retcode":100000,"r...omain login error"}\n'
[2018-01-12 19:06:00] [ERROR] 接收消息出错，开始测试登录 cookie 是否过期...
[2018-01-12 19:06:00] [INFO] 登录成功。登录账号：淡定(1098880928)
[2018-01-12 19:06:00] [INFO] 登录 cookie 尚未过期
[2018-01-12 19:06:01] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"retcode":100000,"r...omain login error"}\n'
[2018-01-12 19:06:01] [ERROR] 接收消息出错，开始测试登录 cookie 是否过期...
[2018-01-12 19:06:02] [INFO] 登录成功。登录账号：淡定(1098880928)
[2018-01-12 19:06:02] [INFO] 登录 cookie 尚未过期
[2018-01-12 19:06:03] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"retcode":100000,"r...omain login error"}\n'
[2018-01-12 19:06:03] [ERROR] 接收消息出错，开始测试登录 cookie 是否过期...
[2018-01-12 19:06:03] [INFO] 登录成功。登录账号：淡定(1098880928)
[2018-01-12 19:06:03] [INFO] 登录 cookie 尚未过期
[2018-01-12 19:06:04] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"retcode":100000,"r...omain login error"}\n'
[2018-01-12 19:06:04] [ERROR] 接收消息出错，开始测试登录 cookie 是否过期...
[2018-01-12 19:06:04] [INFO] 登录成功。登录账号：淡定(1098880928)
[2018-01-12 19:06:04] [INFO] 登录 cookie 尚未过期
[2018-01-12 19:06:05] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"retcode":100000,"r...omain login error"}\n'
[2018-01-12 19:06:05] [ERROR] 接收消息出错，开始测试登录 cookie 是否过期...
[2018-01-12 19:06:06] [INFO] 登录成功。登录账号：淡定(1098880928)
[2018-01-12 19:06:06] [INFO] 登录 cookie 尚未过期
[2018-01-12 19:06:07] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"retcode":100000,"r...omain login error"}\n'
[2018-01-12 19:06:07] [ERROR] 接收消息出错，开始测试登录 cookie 是否过期...
[2018-01-12 19:06:07] [INFO] 登录成功。登录账号：淡定(1098880928)
[2018-01-12 19:06:07] [INFO] 登录 cookie 尚未过期
[2018-01-12 19:06:08] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"retcode":100000,"r...omain login error"}\n'
[2018-01-12 19:06:08] [ERROR] 接收消息出错，开始测试登录 cookie 是否过期...
[2018-01-12 19:06:08] [INFO] 登录成功。登录账号：淡定(1098880928)
[2018-01-12 19:06:08] [INFO] 登录 cookie 尚未过期
[2018-01-12 19:08:10] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"errmsg":"error","r...st[59.988725683s]"}\n'
[2018-01-12 19:08:10] [ERROR] 接收消息出错，开始测试登录 cookie 是否过期...
[2018-01-12 19:08:10] [INFO] 登录成功。登录账号：淡定(1098880928)
[2018-01-12 19:08:10] [INFO] 登录 cookie 尚未过期
[2018-01-12 19:11:11] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"errmsg":"error","r...st[59.988844598s]"}\n'
[2018-01-12 19:11:11] [ERROR] 接收消息出错，开始测试登录 cookie 是否过期...
[2018-01-12 19:11:11] [INFO] 登录成功。登录账号：淡定(1098880928)
[2018-01-12 19:11:11] [INFO] 登录 cookie 尚未过期
[2018-01-12 19:14:12] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"errmsg":"error","r...st[59.984925654s]"}\n'
[2018-01-12 19:14:12] [ERROR] 接收消息出错，开始测试登录 cookie 是否过期...
[2018-01-12 19:14:12] [INFO] 登录成功。登录账号：淡定(1098880928)
[2018-01-12 19:14:12] [INFO] 登录 cookie 尚未过期
[2018-01-12 19:17:14] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"errmsg":"error","r...st[59.956472091s]"}\n'
[2018-01-12 19:17:14] [ERROR] 接收消息出错，开始测试登录 cookie 是否过期...
[2018-01-12 19:17:14] [INFO] 登录成功。登录账号：淡定(1098880928)
[2018-01-12 19:17:14] [INFO] 登录 cookie 尚未过期
[2018-01-12 19:20:15] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"errmsg":"error","r...st[59.958431381s]"}\n'
[2018-01-12 19:20:15] [ERROR] 接收消息出错，开始测试登录 cookie 是否过期...
[2018-01-12 19:20:15] [INFO] 登录成功。登录账号：淡定(1098880928)
[2018-01-12 19:20:15] [INFO] 登录 cookie 尚未过期
[2018-01-12 19:23:16] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"errmsg":"error","r...st[59.986195168s]"}\n'
[2018-01-12 19:23:16] [ERROR] 接收消息出错，开始测试登录 cookie 是否过期...
[2018-01-12 19:23:17] [INFO] 登录成功。登录账号：淡定(1098880928)
[2018-01-12 19:23:17] [INFO] 登录 cookie 尚未过期
[2018-01-12 19:26:18] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"errmsg":"error","r...st[59.987274979s]"}\n'
[2018-01-12 19:26:18] [ERROR] 接收消息出错，开始测试登录 cookie 是否过期...
[2018-01-12 19:26:18] [INFO] 登录成功。登录账号：淡定(1098880928)
[2018-01-12 19:26:18] [INFO] 登录 cookie 尚未过期
[2018-01-12 20:23:09] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"errmsg":"error","r...st[59.988891854s]"}\n'
[2018-01-12 20:23:09] [ERROR] 接收消息出错，开始测试登录 cookie 是否过期...
[2018-01-12 20:23:09] [INFO] 登录成功。登录账号：淡定(1098880928)
[2018-01-12 20:23:09] [INFO] 登录 cookie 尚未过期
[2018-01-12 21:10:58] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"errmsg":"error","r...st[59.985045881s]"}\n'
[2018-01-12 21:10:58] [ERROR] 接收消息出错，开始测试登录 cookie 是否过期...
[2018-01-12 21:10:58] [INFO] 登录成功。登录账号：淡定(1098880928)
[2018-01-12 21:10:58] [INFO] 登录 cookie 尚未过期

**Comment by randomyao22** [comment]
我也是这个情况。

**Comment by pandolia** [comment]
可能是协议又改了

**Comment by pandolia** [comment]
是协议变更引起的问题，新发布了 v2.3.9 版修复了此问题。

**Comment by 1098880928aa** [comment]
已更新，测试中，谢谢及时修复

**Comment by Tiande** [comment]
@pandolia 更新 v2.3.9 后还是出现收不到信息的问题，同时也没有任何报错

**Comment by ttionya** [comment]
我这边会在最后一个人回复后1min后出现`{'errmsg': 'error', 'retcode': 100012, 'retmsg': 'cmd[qconnect.0], errmsg[RecvTimeout], cost[59.956365374s]'}`这样的错误。

然后一段时间后，会每秒出现一个 `{'errmsg': 'error', 'retcode': 0, 'retmsg': 'ok'}`，这时机器人无法收到任何信息，手动 `qq restart` 重启后恢复，一段时间后又这样。

**Comment by pandolia** [comment]
报 {'errmsg': 'error', 'retcode': 100012, 'retmsg': 'cmd[qconnect.0], errmsg[RecvTimeout], cost[59.956365374s]'} 不影响使用的，只是表示当前没有新的消息。

**Comment by pandolia** [comment]
每秒出现 {'errmsg': 'error', 'retcode': 0, 'retmsg': 'ok'} 这个问题我刚刚碰到。不知道怎么回事，可能是协议又改了。。。

**Comment by pandolia** [comment]
昨天重启了一下， {'errmsg': 'error', 'retcode': 0, 'retmsg': 'ok'} 的问题貌似又不出现了。

**Comment by 1098880928aa** [comment]
环境：Python3
qqbot: 2.3.9
qqbot重启时间：17:20（看时间应该不是重启qqbot导致的问题）
情况描述：之前能正常接收到消息，报这个错误之后，就收不到消息了，是不是跳出loop循环了

[2018-01-15 19:37:19] [ERROR] 读取二维码文件 C:\Users\Administrator\.qqbot-tmp\1b420fef3b2c49f29687402c876cc41f.png 出错：[Errno 2] No such file or directory: '
C:\\Users\\Administrator\\.qqbot-tmp\\1b420fef3b2c49f29687402c876cc41f.png'
[2018-01-15 19:48:32] [ERROR] 读取二维码文件 C:\Users\Administrator\.qqbot-tmp\1b420fef3b2c49f29687402c876cc41f.png 出错：[Errno 2] No such file or directory: 'C:\\Users\\Administrator\\.qqbot-tmp\\1b420fef3b2c49f29687402c876cc41f.png'
[2018-01-16 07:33:41] [ERROR] 二维码 HTTP 服务器 在处理 183.57.54.43:56241 的请
求时发生错误，'utf-8' codec can't decode byte 0xff in position 8: invalid start byte
Traceback (most recent call last):
  File "c:\python\python36\lib\site-packages\qqbot\mysocketserver.py", line 63,
in onData
    resp = self.response(data)
  File "c:\python\python36\lib\site-packages\qqbot\qrcodeserver.py", line 21, in
 response
    request = BYTES2STR(request)
  File "c:\python\python36\lib\site-packages\qqbot\common.py", line 17, in <lamb
da>
    BYTES2STR = lambda s: s.decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 8: invalid
start byte
[2018-01-16 07:33:41] [ERROR] 读取二维码文件 C:\Users\Administrator\.qqbot-tmp\1b420fef3b2c49f29687402c876cc41f.png 出错：[Errno 2] No such file or directory: '
C:\\Users\\Administrator\\.qqbot-tmp\\1b420fef3b2c49f29687402c876cc41f.png'
[2018-01-16 07:33:41] [ERROR] 二维码 HTTP 服务器 在处理 183.57.54.43:56629 的请

**Comment by pandolia** [comment]
@1098880928aa 出现这个问题稍微等一会就可以收到消息了。或者关闭二维码服务器，也不会出现这个问题。

**Comment by pandolia** [comment]
@ttionya  {'errmsg': 'error', 'retcode': 0, 'retmsg': 'ok'} 的问题已修复。

**Comment by blackfiregh** [comment]
是不是python3.6 的才有qqbot: 2.3.9版本？
