### ISSUE TITLE
PasswordLogin插件，出现mq未定义Error。

### ISSUE THREAD

**Issue by yuansuye** [pandolia/qqbot#278]
初步判断是因为进入了w.qq.com页面后，未跳转到web2.qq.com，因此无法获取mq信息。
---
ERROR:Utf8Logger:用户名-密码登录失败，原因：Message: ReferenceError: mq is not defined
Traceback (most recent call last):
  File "C:\Users\ryan\.qqbot-tmp\plugins\passwordlogin.py", line 56, in Login
    self.newLogin(conf)
  File "C:\Users\ryan\.qqbot-tmp\plugins\passwordlogin.py", line 102, in newLogin
    self.ptwebqq = driver.execute_script('return mq.ptwebqq')
  File "d:\programdata\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 546, in execute_script
    'args': converted_args})['value']
  File "d:\programdata\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "d:\programdata\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: ReferenceError: mq is not defined

**Comment by heyidi** [comment]
同样的问题...
JavascriptException: Message: ReferenceError: mq is not defined

**Comment by babyfiv5** [comment]
我也遇到了，监控登录过程发现并不是qqbot本身的原因，可能是http://w.qq.com界面发生变化了，不能直接获取到登录信息，把密码登录插件里边的所有地址都改成http://web2.qq.com就好了，我目前是这样解决的。

**Comment by yuansuye** [comment]
@babyfiv5 啊，我把`driver.get('http://web2.qq.com')`在后面补了一遍，没用，原来可以这样干。感谢哈哈。顺便当小白真不好受。

**Comment by iWoz** [comment]
@babyfiv5 是所有地址么，我这么改好像还是登不上去，能否把你的passwordlogin,py发个gist？

**Comment by babyfiv5** [comment]
就把所有http://w.qq.com替换成http://web2.qq.com，这只是我现在用的方法，尝试了几次都可以登录。
https://gist.github.com/babyfiv5/17dbb1713a682cbba9c18ccc20a755e3

**Comment by iWoz** [comment]
@babyfiv5  OK 因为你说把所有url全部换掉，我以为最开始的m.qzone.com也要换掉
