### ISSUE TITLE
Docker 环境下运行出错

### ISSUE THREAD

**Issue by auroreme** [pandolia/qqbot#30]
如下执行情况：

```
root@Aurore:~# docker run -it --rm -p 8189:8189 ubuntu:trusty /bin/bash
root@b6142e3bc84c:/# apt-get update
root@b6142e3bc84c:/# apt-get install -y python python-setuptools
root@b6142e3bc84c:/# easy_install pip
root@b6142e3bc84c:/# pip install qqbot
root@b6142e3bc84c:/# pip install flask
root@b6142e3bc84c:/# qqbot -q 123456789 -p 8188 -ip 0.0.0.0 -hp 8189 -r -d
[2017-01-17 04:07:11] [INFO] QQBot-v2.0.2
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 872, in emit
    stream.write(fs % msg)
  File "/usr/local/lib/python2.7/dist-packages/qqbot/utf8logger.py", line 11, in <l
ambda>
    lambda s: writer.write(s.decode(coding).encode(wcoding, 'igonre'))
LookupError: unknown error handler name 'igonre'
Logged from file qconf.py, line 183
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 872, in emit
    stream.write(fs % msg)
  File "/usr/local/lib/python2.7/dist-packages/qqbot/utf8logger.py", line 11, in <l
ambda>
    lambda s: writer.write(s.decode(coding).encode(wcoding, 'igonre'))
LookupError: unknown error handler name 'igonre'
Logged from file qconf.py, line 184

root@06ccae6fa6c5:/# nohup qqbot -q 123456789 -p 8188 -ip 0.0.0.0 -hp 8189 -r -d > qqbot.log 2>&1 &
root@06ccae6fa6c5:/# tail qqbot.log
[2017-01-17 04:12:55] [INFO] QQBot-v2.0.2
[2017-01-17 04:12:55] [INFO] 配置完成
[2017-01-17 04:12:55] [INFO] 用户名： 无
[2017-01-17 04:12:55] [INFO] 登录方式：自动（qq=123456789）
[2017-01-17 04:12:55] [INFO] 命令行服务器端口号：8188
[2017-01-17 04:12:55] [INFO] HTTP 服务器 ip ：0.0.0.0
[2017-01-17 04:12:55] [INFO] HTTP 服务器端口号：8189
[2017-01-17 04:12:55] [INFO] 用于接收二维码的邮箱账号：无
[2017-01-17 04:12:55] [INFO] 邮箱服务授权码：无
[2017-01-17 04:12:55] [INFO] 调试模式：开启
[2017-01-17 04:12:55] [INFO] 掉线后自动重启：是
[2017-01-17 04:12:55] [INFO] 开始自动登录...

root@b6142e3bc84c:/# exit
```

直接通过命令行运行 `qqbot` 全是报错，而输出重定向却可以看到正确输出？

**Comment by auroreme** [comment]
`CentOS` 下异常一致；`Debian` 下报错缺少 `certifi` 依赖，然而 `pip list`  显示已经安装；`Alpine` 正常。

**Comment by pandolia** [comment]
汗。第一个错误是因为 File "/usr/local/lib/python2.7/dist-packages/qqbot/utf8logger.py", line 11, 中的 ‘igonre’ 写错了，应该为 'ignore' 。
在我的系统中，用 'igonre' 居然没报错。。。

**Comment by pandolia** [comment]
Debian下我这边是可以用的，不过我用的是 mate 图形系统。

**Comment by pandolia** [comment]
你可以试一下下载文件后直接运行 qqbot.py 文件。

**Comment by pandolia** [comment]
HTTP 服务器 ip 不能设置为 0.0.0.0 ，应该设置为实际 ip ，否则邮箱中收到的图片链接就是 http://0.0.0.0:8189/qqbot/qrcode 。
无论设置为什么 ip ，都会在 0.0.0.0 上进行监听。设置的值只是用来告诉用户的图片链接的。

**Comment by auroreme** [comment]
我所指的第一个异常是只显示一连串的 `ignore` ，正常的 `INFO` 完全不输出。

**Comment by auroreme** [comment]
我这没有 `GUI` 界面，纯终端环境，

**Comment by auroreme** [comment]
我这测试环境是 `SSH` 远程连接到服务器上，没有 `GUI` 界面。

**Comment by pandolia** [comment]
你试试把 utf8logger.py 中第17行和第21行的 sys.stderr 改为 sys.stdout ，看看能不能输出 INFO 等信息。

**Comment by auroreme** [comment]
好的谢谢，搭建问题已经解决。
