### ISSUE TITLE
扫码后无法正常登录

### ISSUE THREAD

**Issue by npfjcg** [pandolia/qqbot#303]
[2018-03-26 23:16:45] [INFO] 等待二维码扫描及授权...
[2018-03-26 23:17:09] [INFO] 已获授权
[2018-03-26 23:17:11] [INFO] 已获取ptwebqq
[2018-03-26 23:19:45] [ERROR] 第5次请求“http://s.web2.qq.com/api/getvfwebqq”时出现 网络错误 HTTPConnectionPool(host='s.web2.qq.com', port=80): Read timed out. (read timeout=30), html=''
Traceback (most recent call last):
  File "/usr/local/bin/qqbot", line 11, in <module>
    sys.exit(RunBot())
  File "/usr/local/lib/python2.7/dist-packages/qqbot/qqbotcls.py", line 93, in RunBot
    runBot(argv)
  File "/usr/local/lib/python2.7/dist-packages/qqbot/qqbotcls.py", line 45, in runBot
    bot.Login(argv)
  File "/usr/local/lib/python2.7/dist-packages/qqbot/qqbotcls.py", line 108, in Login
    session, contactdb = QLogin(self.conf)
  File "/usr/local/lib/python2.7/dist-packages/qqbot/qsession.py", line 50, in QLogin
    session.Login(conf)
  File "/root/.qqbot-tmp/plugins/passwordlogin.py", line 71, in Login
    BasicQSession.Login(self, conf)
  File "/usr/local/lib/python2.7/dist-packages/qqbot/basicqsession.py", line 36, in Login
    self.getVfwebqq()
  File "/usr/local/lib/python2.7/dist-packages/qqbot/basicqsession.py", line 151, in getVfwebqq
    Origin = 'http://s.web2.qq.com'
  File "/usr/local/lib/python2.7/dist-packages/qqbot/basicqsession.py", line 415, in smartRequest
    raise RequestError
qqbot.basicqsession.RequestError
[2018-03-26 23:19:45] [CRITICAL] QQBOT 异常停止（code=1）

**Comment by LonelySteve** [comment]
同~~QAQ，刚准备提issue来着。。我还以为是我个人网络问题

**Comment by pandolia** [comment]
现在应该好了。

**Comment by a1822794** [comment]
刚刚试着还是不行

**Comment by pandolia** [comment]
试试用 passwordlogin 插件吧，用密码登录，不用扫码。

**Comment by YoshinoSakura** [comment]
passwordlogin似乎也不行..webqq的网页登陆了都是一片空白

**Comment by AndreamApp** [comment]
同这个问题QAQ

**Comment by fritx** [comment]
我这也是

**Comment by pzli** [comment]
今天也报这个问题了

**Comment by ChangyuYan** [comment]
今天我也遇到这个问题了

**Comment by FlowersYu** [comment]
我也是

**Comment by Cloudifold** [comment]
我也是qwq

**Comment by Vismorey** [comment]
我也有这个问题
