### ISSUE TITLE
GroupShut有问题

### ISSUE THREAD

**Issue by Micrafast** [pandolia/qqbot#321]
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\qqbot\qqbotcls.py", line 99, in _call
    func(*args, **kwargs)
  File "C:\Users\Administrator\.qqbot-tmp\plugins\qqgm.py", line 69, in onQQMessage
    bot.GroupShut(contact, member, t=mutetime)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\qqbot\groupmanager.py", line 139, in GroupShut
    self.groupShut, t
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\qqbot\groupmanager.py", line 79, in membsOperation
    for m in membs:
TypeError: 'GroupMember' object is not iterable
报错如上，尝试禁言就有错

**Comment by Micra-90938jfkj** [comment]
分析了一下代码，明白是要用一个列表放人了，但是接下来的常识里调用了这个函数虽然没报错但还是禁言不了 怎么回事= =

**Comment by pandolia** [comment]
群管理的接口已失效，抱歉。

**Comment by Micra-90938jfkj** [comment]
那么可以修复吗。。。。我真的比较需要群管理的接口 省得我群里面管理员团队自己来管违规

**Comment by Micrafast** [comment]
貌似是腾讯关闭了群管理接口 估计是修不了了 我先关了这个issue....
