### ISSUE TITLE
用户名密码登陆失败，报RequestError

### ISSUE THREAD

**Issue by nicbh** [pandolia/qqbot#325]
昨天自动重启的时候用户名密码登陆就失败了报RequestError，今天自动重启依然报错。杀进程后手动重启也是一样的错误，日志如下：
```
[2018-05-19 08:01:04] [INFO] QQBot-v2.3.10
[2018-05-19 08:01:04] [INFO] Python 3.5.3
[2018-05-19 08:01:04] [INFO] 工作目录：/root/.qqbot-tmp
[2018-05-19 08:01:04] [INFO] 配置文件：/root/.qqbot-tmp/v2.3.conf
[2018-05-19 08:01:04] [INFO] 用户名：server2
[2018-05-19 08:01:04] [INFO] 登录方式：自动（qq=**）
[2018-05-19 08:01:04] [INFO] 命令行服务器端口号：8188
[2018-05-19 08:01:04] [INFO] 二维码服务器 ip ：无
[2018-05-19 08:01:04] [INFO] 二维码服务器端口号：无
[2018-05-19 08:01:04] [INFO] 用于接收二维码的邮箱账号：**
[2018-05-19 08:01:04] [INFO] 邮箱服务授权码：******
[2018-05-19 08:01:04] [INFO] 以文本模式显示二维码：是
[2018-05-19 08:01:04] [INFO] 调试模式：开启
[2018-05-19 08:01:04] [INFO] 掉线后自动重启：是
[2018-05-19 08:01:04] [INFO] 后台模式（daemon 模式）：是
[2018-05-19 08:01:04] [INFO] 启动方式：快速启动（登录成功后立即启动）
[2018-05-19 08:01:04] [INFO] 插件目录0：/root/.qqbot-tmp
[2018-05-19 08:01:04] [INFO] 插件目录1：/root/.qqbot-tmp/plugins
[2018-05-19 08:01:04] [INFO] 启动时需要加载的插件：['qqbot.plugins.sampleslots', 'schedrestart', 'passwordlogin', 'mqqbot.deal']
[2018-05-19 08:01:04] [INFO] 成功：加载插件 qqbot.plugins.sampleslots（回调函数['onInterval', 'onUpdate', 'onInit', 'onStartupComplete', 'onQQMessage', 'onUnplug', 'onQrcode', 'onExit', 'onPlug']、定时任务[]）
[2018-05-19 08:01:04] [INFO] 成功：加载插件 schedrestart（回调函数['onUnplug', 'onPlug']、定时任务[]）
[2018-05-19 08:01:04] [INFO] 成功：加载插件 passwordlogin（回调函数['onInit']、定时任务[]）
[2018-05-19 08:01:06] [INFO] 成功：加载插件 mqqbot.deal（回调函数['onQQMessage', 'onExit']、定时任务[]）
[2018-05-19 08:01:06] [DEBUG] qqbot.plugins.sampleslots.onInit
[2018-05-19 08:01:06] [INFO] 开始自动登录...
[2018-05-19 08:01:06] [INFO] 成功从文件 "/root/.qqbot-tmp/v2.3-py3-**.pickle" 中恢复登录信息
[2018-05-19 08:01:09] [WARNING] 自动登录失败，原因：上次保存的登录信息已过期
[2018-05-19 08:01:09] [INFO] 开始手动登录...
[2018-05-19 08:01:09] [INFO] 正在使用“用户名-密码”登录，请耐心等待 1 ~ 3 分钟......
[2018-05-19 08:02:29] [ERROR] 用户名-密码登录失败，原因：
Traceback (most recent call last):
  File "/root/.qqbot-tmp/plugins/passwordlogin.py", line 120, in newLogin
    self.TestLogin()
  File "/usr/local/lib/python3.5/dist-packages/qqbot/basicqsession.py", line 188, in TestLogin
    repeatOnDeny = 0
  File "/usr/local/lib/python3.5/dist-packages/qqbot/basicqsession.py", line 415, in smartRequest
    raise RequestError
qqbot.basicqsession.RequestError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.qqbot-tmp/plugins/passwordlogin.py", line 56, in Login
    self.newLogin(conf)
  File "/root/.qqbot-tmp/plugins/passwordlogin.py", line 122, in newLogin
    self.TestLogin()
  File "/usr/local/lib/python3.5/dist-packages/qqbot/basicqsession.py", line 188, in TestLogin
    repeatOnDeny = 0
  File "/usr/local/lib/python3.5/dist-packages/qqbot/basicqsession.py", line 415, in smartRequest
    raise RequestError
qqbot.basicqsession.RequestError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.qqbot-tmp/plugins/passwordlogin.py", line 120, in newLogin
    self.TestLogin()
  File "/usr/local/lib/python3.5/dist-packages/qqbot/basicqsession.py", line 188, in TestLogin
    repeatOnDeny = 0
  File "/usr/local/lib/python3.5/dist-packages/qqbot/basicqsession.py", line 415, in smartRequest
    raise RequestError
qqbot.basicqsession.RequestError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.qqbot-tmp/plugins/passwordlogin.py", line 58, in Login
    self.newLogin(conf)
  File "/root/.qqbot-tmp/plugins/passwordlogin.py", line 122, in newLogin
    self.TestLogin()
  File "/usr/local/lib/python3.5/dist-packages/qqbot/basicqsession.py", line 188, in TestLogin
    repeatOnDeny = 0
  File "/usr/local/lib/python3.5/dist-packages/qqbot/basicqsession.py", line 415, in smartRequest
    raise RequestError
qqbot.basicqsession.RequestError
[2018-05-19 08:02:29] [INFO] 开始使用“手工扫码”登录......
[2018-05-19 08:02:29] [INFO] 已获取二维码
[2018-05-19 08:02:29] [DEBUG] qqbot.plugins.sampleslots.onQrcode: /root/.qqbot-tmp/ba8ea9384d594302a84dd522986eb8b3.png (484 bytes)
```

**Comment by pandolia** [comment]
由于腾讯的协议变更，密码登录已经失效了。
