### ISSUE TITLE
qqbot 发送邮箱获取验证码登录 

### ISSUE THREAD

**Issue by burning-git** [pandolia/qqbot#344]
[2018-07-11 13:57:08] [WARNING] 无法将二维码发送至邮箱 [Errno 54] Connection reset by peer
Traceback (most recent call last):
  File "/Users/gitburning/Library/Python/2.7/lib/python/site-packages/qqbot/qrcodemanager.py", line 115, in sendEmail
    with self.mailAgent.SMTP() as smtp:
  File "/Users/gitburning/Library/Python/2.7/lib/python/site-packages/qqbot/mailagent.py", line 73, in <lambda>
    self.SMTP = lambda : SMTP(self)
  File "/Users/gitburning/Library/Python/2.7/lib/python/site-packages/qqbot/mailagent.py", line 79, in __init__
    self.server = mail_agent.st_SMTP()
  File "/Users/gitburning/Library/Python/2.7/lib/python/site-packages/qqbot/mailagent.py", line 66, in <lambda>
    self.st_SMTP = lambda : st_SMTP(self.smtp)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 796, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 802, in _get_socket
    new_socket = ssl.wrap_socket(new_socket, self.keyfile, self.certfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 911, in wrap_socket
    ciphers=ciphers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 54] Connection reset by peer

请问是什么问题呢，，邮箱、邮箱授权码也配置了的

**Comment by pandolia** [comment]
估计是网络问题，无法和smtp服务器连接。
