### ISSUE TITLE
win10环境+py27报了一个https的错误（已解决）

### ISSUE THREAD

**Issue by qjaden** [pandolia/qqbot#358]
`Traceback (most recent call last):
  File "c:\users\albert\anaconda3\envs\py27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\albert\anaconda3\envs\py27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Albert\Anaconda3\envs\py27\Scripts\qqbot.exe\__main__.py", line 9, in <module>
  File "c:\users\albert\anaconda3\envs\py27\lib\site-packages\qqbot\qqbotcls.py", line 93, in RunBot
    runBot(argv)
  File "c:\users\albert\anaconda3\envs\py27\lib\site-packages\qqbot\qqbotcls.py", line 45, in runBot
    bot.Login(argv)
  File "c:\users\albert\anaconda3\envs\py27\lib\site-packages\qqbot\qqbotcls.py", line 108, in Login
    session, contactdb = QLogin(self.conf)
  File "c:\users\albert\anaconda3\envs\py27\lib\site-packages\qqbot\qsession.py", line 50, in QLogin
    session.Login(conf)
  File "c:\users\albert\anaconda3\envs\py27\lib\site-packages\qqbot\basicqsession.py", line 33, in Login
    self.prepareSession()
  File "c:\users\albert\anaconda3\envs\py27\lib\site-packages\qqbot\basicqsession.py", line 51, in prepareSession
    'https://ui.ptlogin2.qq.com/cgi-bin/login?daid=164&target=self&'
  File "c:\users\albert\anaconda3\envs\py27\lib\site-packages\qqbot\basicqsession.py", line 323, in urlGet
    return self.session.get(url, timeout=timeout)
  File "c:\users\albert\anaconda3\envs\py27\lib\site-packages\requests\sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\albert\anaconda3\envs\py27\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\albert\anaconda3\envs\py27\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\albert\anaconda3\envs\py27\lib\site-packages\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ui.ptlogin2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/login?daid=164&target=self&style=16&mibao_css=m_webqq&appid=501004106&enable_qlogin=0&no_verifyimg=1&s_url=http%3A%2F%2Fw.qq.com%2Fproxy.html&f_url=loginerroralert&strong_login=1&login_state=10&t=20131024001 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004874B70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
[2018-08-10 11:17:48] [CRITICAL] QQBOT 异常停止（code=1）`

**Comment by pandolia** [comment]
应该是网络问题，过一会再试试。

**Comment by ZhengHui-Z** [comment]
已经解决，需要一个openssl的py库
