### ISSUE TITLE
个例电脑无法使用邮箱发送二维码

### ISSUE THREAD

**Issue by MDeath** [pandolia/qqbot#362]
循环报错以下代码：
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 0: invalid start byte
[2018-08-25 23:39:14] [WARNING] 无法将二维码发送至邮箱XXXXXXXXX@qq.com 'utf-8' codec can't decode byte 0xb7 in position 0: invalid start byte
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\qqbot\qrcodemanager.py", line 115, in sendEmail
    with self.mailAgent.SMTP() as smtp:
  File "c:\programdata\anaconda3\lib\site-packages\qqbot\mailagent.py", line 73, in <lambda>
    self.SMTP = lambda : SMTP(self)
  File "c:\programdata\anaconda3\lib\site-packages\qqbot\mailagent.py", line 79, in __init__
    self.server = mail_agent.st_SMTP()
  File "c:\programdata\anaconda3\lib\site-packages\qqbot\mailagent.py", line 66, in <lambda>
    self.st_SMTP = lambda : st_SMTP(self.smtp)
  File "c:\programdata\anaconda3\lib\smtplib.py", line 1031, in __init__
    source_address)
  File "c:\programdata\anaconda3\lib\smtplib.py", line 261, in __init__
    fqdn = socket.getfqdn()
  File "c:\programdata\anaconda3\lib\socket.py", line 673, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)

**Comment by pandolia** [comment]
这个问题之前有人碰到过，是因为计算机名或系统用户名中含中文的问题，把你的计算机名或系统用户名改为英文就可以了。

**Comment by MDeath** [comment]
ok thank
