### ISSUE TITLE
近期总是这样卡住

### ISSUE THREAD

**Issue by Tiande** [pandolia/qqbot#381]
求解决
```Python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/qqbot/mainloop.py", line 21, in workAt
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/qqbot/qqbotcls.py", line 201, in onPollComplete
    self.onQQMessage(contact, member, content)
  File "/usr/local/lib/python2.7/dist-packages/qqbot/qqbotcls.py", line 248, in func
    _call(f, self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/qqbot/qqbotcls.py", line 99, in _call
    func(*args, **kwargs)
  File "/home/tiande/.qqbot-tmp/plugins/attr.py", line 116, in onQQMessage
    bot.SendTo(contact, housql.getFace(myContent))
  File "/usr/local/lib/python2.7/dist-packages/qqbot/basicqsession.py", line 307, in SendTo
    self.send(contact.ctype, contact.uin, front, epCodes)
  File "/usr/local/lib/python2.7/dist-packages/qqbot/basicqsession.py", line 267, in send
    expectedCodes = epCodes
  File "/usr/local/lib/python2.7/dist-packages/qqbot/basicqsession.py", line 365, in smartRequest
    'hoty=9999&rand=%s') % random.randint(10000, 99999)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt
```

**Comment by pandolia** [comment]
卡在发消息的地方。把下面这行注释掉试试：
bot.SendTo(contact, housql.getFace(myContent))
