### ISSUE TITLE
使用树莓派运行qqbot时，提示无法弹出二维码图片

### ISSUE THREAD

**Issue by Williamongh** [pandolia/qqbot#46]
环境是raspbian最新版，python2.7.9，找到对应目录，可以看到二维码图片。
[2017-02-16 15:46:12] [INFO] QQBot-v2.0.6
[2017-02-16 15:46:12] [INFO] 配置完成
[2017-02-16 15:46:12] [INFO] 用户名： 无
[2017-02-16 15:46:12] [INFO] 登录方式：手动
[2017-02-16 15:46:12] [INFO] 命令行服务器端口号：8188
[2017-02-16 15:46:12] [INFO] HTTP 服务器 ip ：无
[2017-02-16 15:46:12] [INFO] HTTP 服务器端口号：无
[2017-02-16 15:46:12] [INFO] 用于接收二维码的邮箱账号：无
[2017-02-16 15:46:12] [INFO] 邮箱服务授权码：无
[2017-02-16 15:46:12] [INFO] 调试模式：关闭
[2017-02-16 15:46:12] [INFO] 掉线后自动重启：否
[2017-02-16 15:46:12] [INFO] 开始手动登录...
[2017-02-16 15:46:12] [INFO] 登录 Step1 - 获取二维码
[2017-02-16 15:46:12] [WARNING] 无法弹出二维码图片 file:///home/pi/.qqbot-tmp/3f316aa2918e447099f1a3b3e6053fbf.png 。[Errno 2] No such file or directory
[2017-02-16 15:46:15] [INFO] 登录 Step2 - 等待二维码扫描及授权
[2017-02-16 15:46:19] [INFO] 登录 Step2 - 等待二维码扫描及授权

谢谢！

**Comment by pandolia** [comment]
Linux下，需要安装有GNOME虚拟文件系统gvfs才能弹出图片。见qrcodemanager.py文件第121行：subprocess.call(['gvfs-open', filename]）。你试试看单独运行这一行能不能打开图片。

**Comment by pandolia** [comment]
如果系统中没有图形界面，建议使用服务器模式或邮件模式来显示二维码。

**Comment by Williamongh** [comment]
你好，已安装gvfs，版本号1.22.2-1
用VNC远程控制桌面，确实无法显示图片，用邮箱应该可以解决。
另外建议 是否可以增加“屏蔽群消息”的功能，或者屏蔽指定联系人/群的消息。
感谢！

**Comment by pandolia** [comment]
那你的系统中可以运行 subprocess.call(['gvfs-open', ‘/home/pi/.qqbot-tmp/3f316aa2918e447099f1a3b3e6053fbf.png’]） 吗？

增加“屏蔽指定联系人/群”的功能应该比较好实现，将 qqbot.py 文件中 QQBot.onPullComplete 中下列语句：

    if ctype == 'buddy':
        memberName = ''
        INFO('来自 %s 的消息: "%s"' % (str(contact), content))
    else:
        memberName = contact.GetMemberName(memberUin)
        INFO('来自 %s[成员“%s”] 的消息: "%s"' % \
             (str(contact), memberName, content))

稍微改改就可以了。例如改为：

    if ctype == 'buddy':
        memberName = ''
        if contact.qq != UNWANTED_QQ:
            INFO('来自 %s 的消息: "%s"' % (str(contact), content))
    else:
        memberName = contact.GetMemberName(memberUin)
        if contact.qq != UNWANTED_QQ:
            INFO('来自 %s[成员“%s”] 的消息: "%s"' % (str(contact), memberName, content))

**Comment by Williamongh** [comment]
仍然不可以。
>>> subprocess.call(['gvfs-open','/home/pi/.qqbot-tmp/4463de7cbe5d48f8a2fa4e38255b7715.png'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by pandolia** [comment]
搞不懂为什么会找不到这个文件。。。你试试在命令行输入：
gvfs-open /home/pi/.qqbot-tmp/4463de7cbe5d48f8a2fa4e38255b7715.png
看能不能打开图片。

**Comment by Williamongh** [comment]
显示command not found 。。。
但是确实有安装gvfs。。

**Comment by pandolia** [comment]
看来是没有 gvfs-open 这个命令。你可以找下系统中打开图片的默认程序是什么。再改一下 subprocess.call 那一行就可以啦。

**Comment by Williamongh** [comment]
嗯好的，再次感谢！

**Comment by pandolia** [comment]
我已经修改了 qrcodemanager.py 等文件，增加了 shotwell 的支持。详见：https://github.com/pandolia/qqbot/commit/53164b56a8de0a95940e057e8d79b06378ecdb8b
