### ISSUE TITLE
由于facemap异常停止

### ISSUE THREAD

**Issue by zjuchenyuan** [pandolia/qqbot#82]
```
[2017-03-28 00:04:23] [CRITICAL] qsession.Poll 方法出错
Traceback (most recent call last):
  File "/mnt/d/Seafile/Developer/qqbot/qqbot/qqbotcls.py", line 121, in pollForever
    result = self.poll()
  File "/mnt/d/Seafile/Developer/qqbot/qqbot/basicqsession.py", line 204, in Poll
    content = FaceReverseParse(result['value']['content'])
  File "/mnt/d/Seafile/Developer/qqbot/qqbot/facemap.py", line 133, in FaceReverseParse
    for m in pollContent[1:]
  File "/mnt/d/Seafile/Developer/qqbot/qqbot/facemap.py", line 133, in <genexpr>
    for m in pollContent[1:]
KeyError: 212
[2017-03-28 00:04:23] [CRITICAL] QQBOT 异常停止（code=202�
```

**Comment by zjuchenyuan** [comment]
qqbot version: latest
Python version: `3.4.3`
platform: bash on win10

**Comment by pandolia** [comment]
额，尴尬了。我中午改一下。

**Comment by pandolia** [comment]
没考虑到还有其他表情的情况

**Comment by pandolia** [comment]
现在应该好了。你可以再用 pip 安装一下。

**Comment by zjuchenyuan** [comment]
Good job!
