### ISSUE TITLE
bug in v2.1.6

### ISSUE THREAD

**Issue by chenhouwu** [pandolia/qqbot#89]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/qqbot/basicqsession.py", line 255, in SendTo
    self.send(ctype, contact.uin, front)
  File "/usr/local/lib/python2.7/dist-packages/qqbot/basicqsession.py", line 233, in send
    repeatOnDeny=5
  File "/usr/local/lib/python2.7/dist-packages/qqbot/basicqsession.py", line 334, in smartRequest
    retcode = rst('errCode')
TypeError: 'dict' object is not callable
```

**Comment by pandolia** [comment]
额，那里确实是写错了。非常感谢！

**Comment by pandolia** [comment]
已在 v2.1.9 修正。再次感谢！
